project:
  type: website
  output-dir: docs
  resources:
    - resume/

website:
  title: "Vidhi A. Sharma"
  description: "Business Analytics Professional"
  site-url: https://vidhisharma2000.github.io/vidhi-portfolio/
  repo-url: https://github.com/VidhiSharma2000/vidhi-portfolio
  favicon: "images/favicon.png"
  page-navigation: true
  back-to-top-navigation: true
  
  navbar:
    pinned: true
    background: light
    search: true
    right:
      - icon: linkedin
        href: https://in.linkedin.com/in/17vidhisharma
      - icon: github
        href: https://github.com/VidhiSharma2000
      - icon: envelope
        href: "mailto:sharmavidhi3008@gmail.com"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Contact"
        href: contact.qmd

  page-footer:
    left: "© 2025 Vidhi A. Sharma. All rights reserved."
    right:
      - icon: github
        href: https://github.com/VidhiSharma2000
      - icon: linkedin
        href: https://in.linkedin.com/in/17vidhisharma

format:
  html:
    theme: 
      light: [sandstone, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    page-layout: full
    code-copy: true
    code-line-numbers: true
    highlight-style: github
    smooth-scroll: true
    link-external-newwindow: true
    fontsize: 1rem