project:
  type: website
  output-dir: docs

website:
  title: "Vidhi A. Sharma"
  navbar:
    left:
      - href: "#about-me"
        text: "About Me"
      - href: "#education"
        text: "Education"
      - href: "#skills"
        text: "Skills"
      - href: "#experience"
        text: "Experience"
      - href: "#projects"
        text: "Projects"
      - href: "#contact"
        text: "Contact"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
